# createDatabaseIfNotExist=true creará la base de datos automáticamente en tu XAMPP/Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/db_farmacia_ventas?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=980626
server.port=8084

# =========================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# =========================================================================
# 'update' creará las tablas 'ventas' y 'detalle_ventas' de forma automática al dar Play
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================================
# TIMEOUTS PARA COMUNICACIÓN SINCÓNICA CON OPENFEIGN (Inventario)
# =========================================================================
# Evita que las solicitudes se queden congeladas si el inventario tarda en responder
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000