# Puerto único para el microservicio de Inventario
server.port=8082

# Configuración de la Base de Datos de Inventario
spring.datasource.url=jdbc:mysql://localhost:3306/db_farmacia_inventario?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=980626

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
