server.port=8083
spring.application.name=notificaciones-service

# Habilitar soporte para OpenFeign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
